spring.application.name=expensetracking

spring.profiles.active=test

spring.jpa.open-in-view=false

api.prefix=api/v1

logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE

security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:*}

security.jwt.secret=${JWT_SECRET:ZXNnLXJlc2lkdW9zLWFwaS1zZWNyZXQta2V5LWZvci1hY2FkZW1pYy1wdXJwb3Nlcy0yMDI1}